/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.LoginController;
import dao.DaoSeguridad;
import generals.Contans;
import generals.Email;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Programador 1
 */
public final class jLogin extends javax.swing.JFrame {

    DaoSeguridad daoSeguridad = new DaoSeguridad();
    Email email = new Email();
    LoginController loginController;

    public jLogin() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/img/$.png")).getImage());
        this.setTitle("MAXMAIL");
        setLocationRelativeTo(null);
        this.setResizable(false);
        verificarSeguridad();
        loginController = new LoginController(this);
    }

    public void verificarSeguridad() {
        try {
            String nombrePc;
            nombrePc = InetAddress.getLocalHost().getHostName();
            if (daoSeguridad.getPc(nombrePc)) {
                if (!daoSeguridad.getVerificarComf(nombrePc)) {
                    confirmarCodigo(nombrePc);
                }
            } else {
                int key = genererNCodigo();
                // this.jMenuBar1.setEnabled(false);
                if (daoSeguridad.insertPC(nombrePc, key)) {
                    try {
                        email.enviarSistema(Contans.CORREO_SERVIDOR_DEFAULT,
                                Contans.CORREO_ADMIN_ENVIO,
                                Contans.CORREO_PASS_DEFAULT,
                                Contans.CORREO_PORT_DEFAULT,
                                "CLAVE DE ACCESO AL PC " + nombrePc, "El computador de nombre "
                                + nombrePc
                                + " requiere permisos su codigo es: " + key,
                                Contans.CORREO_ADMIN_RECIBE, true, true);
                        confirmarCodigo(nombrePc);
                    } catch (MessagingException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                        Logger.getLogger(jprincipal.class.getName()).log(Level.SEVERE, null, ex);   
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "problema al autenticar el servicio, reinstalar nuevamente");
                }
            }
        } catch (UnknownHostException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            Logger.getLogger(jprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void confirmarCodigo(String nombrePc) {
        String resultado = JOptionPane.showInputDialog("¡Por favor digita el codigo de seguridad que hemos enviado al correo del administrador del sistema!");
        if (resultado != null) {
            if (daoSeguridad.codigoSeguridad(resultado, nombrePc)) {
                JOptionPane.showMessageDialog(null, "La instalacion se realizo correctamente.");
            } else {
                confirmarCodigo(nombrePc);
            }
        } else {
            confirmarCodigo(nombrePc);
        }
    }

    public static int genererNCodigo() {
        return (int) (100000 * Math.random());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btnAcess = new javax.swing.JButton();
        Creditos = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        Rotate = new javax.swing.JLabel();
        versionTXT = new javax.swing.JLabel();
        versionCD = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLayeredPane1.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Garamond", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USUARIO");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 255, 255)));
        jLabel1.setOpaque(true);
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 101, 240, -1));

        txtUsuario.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 255, 255)));
        txtUsuario.setOpaque(false);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jLayeredPane1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 240, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Garamond", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONTRASEÑA");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 255, 255)));
        jLabel2.setOpaque(true);
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 240, 20));

        txtPass.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        txtPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPass.setToolTipText("");
        txtPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 255, 255)));
        txtPass.setOpaque(false);
        jLayeredPane1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 240, 30));
        txtPass.getAccessibleContext().setAccessibleName("");

        btnAcess.setBackground(new java.awt.Color(0, 0, 0));
        btnAcess.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        btnAcess.setForeground(new java.awt.Color(255, 255, 255));
        btnAcess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-login.png"))); // NOI18N
        btnAcess.setText("Entrar");
        btnAcess.setToolTipText("");
        btnAcess.setBorder(null);
        btnAcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnAcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 126, 42));

        Creditos.setBackground(new java.awt.Color(0, 0, 0));
        Creditos.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        Creditos.setForeground(new java.awt.Color(255, 255, 255));
        Creditos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Creditos.setText("Derechos Reservado. ZeusBlack - Poseidon © ");
        jLayeredPane1.add(Creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 270, -1));

        icon1.setBackground(new java.awt.Color(0, 0, 0));
        icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-user.png"))); // NOI18N
        icon1.setPreferredSize(new java.awt.Dimension(50, 96));
        jLayeredPane1.add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 240, 50));
        icon1.getAccessibleContext().setAccessibleParent(icon1);

        icon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-password.png"))); // NOI18N
        jLayeredPane1.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 240, 40));

        btnsalir.setBackground(new java.awt.Color(0, 0, 0));
        btnsalir.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-cancelar.png"))); // NOI18N
        btnsalir.setBorder(null);
        btnsalir.setContentAreaFilled(false);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 30, -1));

        Rotate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Rotate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/matrix1.gif"))); // NOI18N
        jLayeredPane1.add(Rotate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 620, 280));

        versionTXT.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        versionTXT.setText("Versión Actual:");
        jLayeredPane1.add(versionTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 20));

        versionCD.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        versionCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionCD.setText("1.2.7");
        jLayeredPane1.add(versionCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 100, -1));

        Fondo.setBackground(new java.awt.Color(0, 0, 0));
        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondolg.jpg"))); // NOI18N
        Fondo.setText("fondo");
        jLayeredPane1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        getContentPane().add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAcessActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Creditos;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Rotate;
    public javax.swing.JButton btnAcess;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JPasswordField txtPass;
    public javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel versionCD;
    private javax.swing.JLabel versionTXT;
    // End of variables declaration//GEN-END:variables
}
